/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.gui;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author tanma
 */
public class LoginSystem extends javax.swing.JFrame {

    /**
     * Creates new form LoginSystem
     */
    
    //create borders
    Border default_top_border = BorderFactory.createMatteBorder(2, 0, 0, 0, new Color(202,204,204));
    Border red_top_border = BorderFactory.createMatteBorder(2, 0, 0, 0, Color.red);
    
    
    
    public LoginSystem() {
        initComponents();
        
        //center form
        this.setLocationRelativeTo(null);
        
        //set borders
        LabelEmployee.setBorder(default_top_border);
        LabelManager.setBorder(default_top_border);
        
        //call the jlabel mouse click event
        LabelEmployeeMouseClicked(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelEmployee = new javax.swing.JLabel();
        LabelManager = new javax.swing.JLabel();
        PanelEmployee = new javax.swing.JPanel();
        TFEmployeeUsername = new javax.swing.JTextField();
        PasswordFieldEmployee = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login System");

        LabelEmployee.setBackground(new java.awt.Color(255, 255, 255));
        LabelEmployee.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LabelEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEmployee.setText("Employee");
        LabelEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEmployeeMouseClicked(evt);
            }
        });

        LabelManager.setBackground(new java.awt.Color(255, 255, 255));
        LabelManager.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LabelManager.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelManager.setText("Manager");
        LabelManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelManagerMouseClicked(evt);
            }
        });

        TFEmployeeUsername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TFEmployeeUsername.setForeground(new java.awt.Color(153, 153, 153));
        TFEmployeeUsername.setText("Username");

        PasswordFieldEmployee.setForeground(new java.awt.Color(153, 153, 153));
        PasswordFieldEmployee.setText("Tanmayee");
        PasswordFieldEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldEmployeeActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Login");

        javax.swing.GroupLayout PanelEmployeeLayout = new javax.swing.GroupLayout(PanelEmployee);
        PanelEmployee.setLayout(PanelEmployeeLayout);
        PanelEmployeeLayout.setHorizontalGroup(
            PanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEmployeeLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(PanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addGroup(PanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PasswordFieldEmployee)
                        .addComponent(TFEmployeeUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        PanelEmployeeLayout.setVerticalGroup(
            PanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEmployeeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(TFEmployeeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordFieldEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(LabelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelManager, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(PanelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelManager, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEmployeeMouseClicked
        // display the employee panel
        LabelEmployee.setBorder(red_top_border);
        LabelEmployee.setBackground(Color.white); //inactive until customization
        LabelEmployee.setBackground(Color.black); //inactive until customization
        
        LabelManager.setBorder(default_top_border);
        LabelManager.setBackground(Color.black); //inactive until customization
        LabelManager.setBackground(Color.white); //inactive until customization
        
    }//GEN-LAST:event_LabelEmployeeMouseClicked

    private void LabelManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelManagerMouseClicked
        // display the manager panel
        LabelManager.setBorder(red_top_border);
        LabelManager.setBackground(Color.white); //inactive until customization
        LabelManager.setBackground(Color.black); //inactive until customization
        
        LabelEmployee.setBorder(default_top_border);
        LabelEmployee.setBackground(Color.black); //inactive until customization
        LabelEmployee.setBackground(Color.white); //inactive until customization
    }//GEN-LAST:event_LabelManagerMouseClicked

    private void PasswordFieldEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEmployee;
    private javax.swing.JLabel LabelManager;
    private javax.swing.JPanel PanelEmployee;
    private javax.swing.JPasswordField PasswordFieldEmployee;
    private javax.swing.JTextField TFEmployeeUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
