/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package productivizepackage;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author tanma
 */
public class LoginSystem extends javax.swing.JFrame {

    /**
     * Creates new form LoginSystem
     */
    
    //create borders
    Border default_top_border = BorderFactory.createMatteBorder(2, 0, 0, 0, new Color(202,204,204));
    Border red_top_border = BorderFactory.createMatteBorder(2, 0, 0, 0, Color.red);
    
    
    
    public LoginSystem() {
        initComponents();
        
        //center form
        this.setLocationRelativeTo(null);
        
        //set borders
        LabelEmployee.setBorder(default_top_border);
        LabelManager.setBorder(default_top_border);
        
        //call the jlabel mouse click event
        LabelEmployeeMouseClicked(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        LabelLoginSystem = new javax.swing.JLabel();
        PanelLogin = new javax.swing.JPanel();
        LabelEmployee = new javax.swing.JLabel();
        LabelManager = new javax.swing.JLabel();
        PanelEmployee = new javax.swing.JPanel();
        TFEmployeeID = new javax.swing.JTextField();
        PasswordFieldEmployee = new javax.swing.JPasswordField();
        ButtonEmployeeLogin = new javax.swing.JButton();
        PanelManager = new javax.swing.JPanel();
        TFManagerID = new javax.swing.JTextField();
        PasswordFieldManager = new javax.swing.JPasswordField();
        ButtonManagerLogin = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelLoginSystem.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LabelLoginSystem.setText("Login System");

        LabelEmployee.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LabelEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEmployee.setText("Employee");
        LabelEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEmployeeMouseClicked(evt);
            }
        });

        LabelManager.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LabelManager.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelManager.setText("Manager");
        LabelManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelManagerMouseClicked(evt);
            }
        });

        TFEmployeeID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TFEmployeeID.setForeground(new java.awt.Color(153, 153, 153));
        TFEmployeeID.setText("employeeid");
        TFEmployeeID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFEmployeeIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFEmployeeIDFocusLost(evt);
            }
        });
        TFEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEmployeeIDActionPerformed(evt);
            }
        });

        PasswordFieldEmployee.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PasswordFieldEmployee.setForeground(new java.awt.Color(153, 153, 153));
        PasswordFieldEmployee.setText("password");
        PasswordFieldEmployee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFieldEmployeeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFieldEmployeeFocusLost(evt);
            }
        });

        ButtonEmployeeLogin.setText("Login");

        javax.swing.GroupLayout PanelEmployeeLayout = new javax.swing.GroupLayout(PanelEmployee);
        PanelEmployee.setLayout(PanelEmployeeLayout);
        PanelEmployeeLayout.setHorizontalGroup(
            PanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEmployeeLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(PanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonEmployeeLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addGroup(PanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PasswordFieldEmployee)
                        .addComponent(TFEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        PanelEmployeeLayout.setVerticalGroup(
            PanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEmployeeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(TFEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordFieldEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ButtonEmployeeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        PanelManager.setMinimumSize(new java.awt.Dimension(100, 100));

        TFManagerID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TFManagerID.setForeground(new java.awt.Color(153, 153, 153));
        TFManagerID.setText("managerid");
        TFManagerID.setSelectionEnd(10);
        TFManagerID.setSelectionStart(10);
        TFManagerID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFManagerIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFManagerIDFocusLost(evt);
            }
        });
        TFManagerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFManagerIDActionPerformed(evt);
            }
        });

        PasswordFieldManager.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PasswordFieldManager.setForeground(new java.awt.Color(153, 153, 153));
        PasswordFieldManager.setText("password");
        PasswordFieldManager.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFieldManagerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFieldManagerFocusLost(evt);
            }
        });
        PasswordFieldManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldManagerActionPerformed(evt);
            }
        });

        ButtonManagerLogin.setText("Login");
        ButtonManagerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonManagerLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelManagerLayout = new javax.swing.GroupLayout(PanelManager);
        PanelManager.setLayout(PanelManagerLayout);
        PanelManagerLayout.setHorizontalGroup(
            PanelManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelManagerLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(PanelManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ButtonManagerLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFManagerID)
                    .addComponent(PasswordFieldManager, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );
        PanelManagerLayout.setVerticalGroup(
            PanelManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelManagerLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(TFManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordFieldManager, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ButtonManagerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LabelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelManager, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(PanelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                    .addContainerGap(46, Short.MAX_VALUE)
                    .addComponent(PanelManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelManager, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                    .addContainerGap(60, Short.MAX_VALUE)
                    .addComponent(PanelManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(LabelLoginSystem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelLoginSystem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEmployeeMouseClicked
        // display the employee panel
        PanelEmployee.setVisible(true);
        PanelManager.setVisible(false);
        
        //design the Employee Label [on-click]
        LabelEmployee.setBorder(red_top_border);
        LabelEmployee.setBackground(Color.black); 
        LabelEmployee.setForeground(Color.black); 
        
        //design the Manager Label [on-click]
        LabelManager.setBorder(default_top_border);
        LabelManager.setBackground(Color.black); 
        LabelManager.setForeground(Color.black); 
    }//GEN-LAST:event_LabelEmployeeMouseClicked

    private void LabelManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelManagerMouseClicked
        // display the manager panel
        PanelManager.setVisible(true);
        PanelEmployee.setVisible(false);
        
        //design the Manager Label [on-click]
        LabelManager.setBorder(red_top_border);
        LabelManager.setBackground(Color.black); 
        LabelManager.setForeground(Color.black); 
        
        //design the Employee Label [on-click]
        LabelEmployee.setBorder(default_top_border);
        LabelEmployee.setBackground(Color.black); 
        LabelEmployee.setForeground(Color.black); 
    }//GEN-LAST:event_LabelManagerMouseClicked

    private void TFEmployeeIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFEmployeeIDFocusGained
        // if the EmployeeID text = employeeid
        //clear the textfield
        String employeeidValue = TFEmployeeID.getText().trim().toLowerCase();
        
        if(employeeidValue.equals("employeeid"))
        {
            TFEmployeeID.setText("");
            TFEmployeeID.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_TFEmployeeIDFocusGained

    private void TFEmployeeIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFEmployeeIDFocusLost
        // if the textfield is empty -> set the text to 'employeeid'
        String employeeidValue = TFEmployeeID.getText().trim().toLowerCase();
        
        if(employeeidValue.equals("employeeid") || employeeidValue.equals(""))
        {
            TFEmployeeID.setText("employeeid");
            TFEmployeeID.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_TFEmployeeIDFocusLost

    private void PasswordFieldEmployeeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldEmployeeFocusGained
        // if the PasswordFieldEmployee field = password
        //clear the field
        String passValue = String.valueOf(PasswordFieldEmployee.getPassword()).trim().toLowerCase();
        
        if(passValue.equals("password"))
        {
            PasswordFieldEmployee.setText("");
            PasswordFieldEmployee.setForeground(Color.black);
        }
    }//GEN-LAST:event_PasswordFieldEmployeeFocusGained

    private void PasswordFieldEmployeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldEmployeeFocusLost
        // if the textfield is empty -> set the text to 'password'
        String passValue = String.valueOf(PasswordFieldEmployee.getPassword()).trim().toLowerCase();
        
        if(passValue.equals("password") || passValue.equals(""))
        {
            PasswordFieldEmployee.setText("password");
            PasswordFieldEmployee.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PasswordFieldEmployeeFocusLost

    private void TFManagerIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFManagerIDFocusGained
        // if the ManagerID text = managerid
        //clear the textfield
        String manageridValue = TFManagerID.getText().trim().toLowerCase();
        
        if(manageridValue.equals("managerid"))
        {
            TFManagerID.setText("");
            TFManagerID.setForeground(Color.black);
        }
    }//GEN-LAST:event_TFManagerIDFocusGained

    private void TFManagerIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFManagerIDFocusLost
        // if the textfield is empty -> set the text to 'managerid'
        String manageridValue = TFManagerID.getText().trim().toLowerCase();
        
        if(manageridValue.equals("managerid") || manageridValue.equals(""))
        {
            TFManagerID.setText("managerid");
            TFManagerID.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_TFManagerIDFocusLost

    private void PasswordFieldManagerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldManagerFocusGained
        // if the PasswordFieldManager field = password
        //clear the field
        String passValue = String.valueOf(PasswordFieldManager.getPassword()).trim().toLowerCase();
        
        if(passValue.equals("password"))
        {
            PasswordFieldManager.setText("");
            PasswordFieldManager.setForeground(Color.black);
        }
    }//GEN-LAST:event_PasswordFieldManagerFocusGained

    private void PasswordFieldManagerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldManagerFocusLost
        // if the textfield is empty -> set the text to 'password'
        String passValue = String.valueOf(PasswordFieldManager.getPassword()).trim().toLowerCase();
        
        if(passValue.equals("password") || passValue.equals(""))
        {
            PasswordFieldManager.setText("password");
            PasswordFieldManager.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PasswordFieldManagerFocusLost

    private void PasswordFieldManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldManagerActionPerformed

    private void TFEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEmployeeIDActionPerformed

    private void TFManagerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFManagerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFManagerIDActionPerformed

    private void ButtonManagerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonManagerLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonManagerLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEmployeeLogin;
    private javax.swing.JButton ButtonManagerLogin;
    private javax.swing.JLabel LabelEmployee;
    private javax.swing.JLabel LabelLoginSystem;
    private javax.swing.JLabel LabelManager;
    private javax.swing.JPanel PanelEmployee;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPanel PanelManager;
    private javax.swing.JPasswordField PasswordFieldEmployee;
    private javax.swing.JPasswordField PasswordFieldManager;
    private javax.swing.JTextField TFEmployeeID;
    private javax.swing.JTextField TFManagerID;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
