
package com.example.gui;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import com.example.entites.Manager;
import com.example.services.Utilities;
import com.example.tabledao.ProjectDao;
import com.example.viewsdao.ManagerView;

/**
 *
 * @author tanma
 */
public class ManagerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeDashboard
     */

    // to setup the table
    DefaultTableModel model;
    private Object employee;

    public ManagerDashboard(Manager loggedInManager) {
        manager = loggedInManager;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonAddProject = new javax.swing.JButton();
        ButtonEditProject = new javax.swing.JButton();
        ButtonDeleteProject = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TFEmpID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        ButtonAddMilestone = new javax.swing.JButton();
        ButtonEditMilestone = new javax.swing.JButton();
        ButtonDeleteMilestone = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        ButtonMAddTask = new javax.swing.JButton();
        ButtonMEditTask = new javax.swing.JButton();
        ButtonMDeleteTask = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxProjectStatus = new javax.swing.JComboBox<>();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Hello" + " !");

        jLabel2.setText("Manager ID:");

        ButtonAddProject.setText("Add a project");
        ButtonAddProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddProjectActionPerformed(evt);
            }
        });

        ButtonEditProject.setText("Edit a project");
        ButtonEditProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditProjectActionPerformed(evt);
            }
        });

        ButtonDeleteProject.setText("Delete a project");
        ButtonDeleteProject.setMaximumSize(new java.awt.Dimension(99, 23));
        ButtonDeleteProject.setMinimumSize(new java.awt.Dimension(99, 23));
        ButtonDeleteProject.setPreferredSize(new java.awt.Dimension(99, 23));
        ButtonDeleteProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteProjectActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Project ID", "Project name", "Start date", "Due date"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        TFEmpID.setEditable(false);
        TFEmpID.setText(" ");
        TFEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEmpIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Projects");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Milestones");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Milestone ID", "Milestone name", "Deliverables", "Due date", "Status"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        ButtonAddMilestone.setText("Add a milestone");
        ButtonAddMilestone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddMilestoneActionPerformed(evt);
            }
        });

        ButtonEditMilestone.setText("Edit a milestone");
        ButtonEditMilestone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditMilestoneActionPerformed(evt);
            }
        });

        ButtonDeleteMilestone.setText("Delete a milestone");
        ButtonDeleteMilestone.setMaximumSize(new java.awt.Dimension(83, 23));
        ButtonDeleteMilestone.setMinimumSize(new java.awt.Dimension(83, 23));
        ButtonDeleteMilestone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteMilestoneActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null }
                },
                new String[] {
                        "Employee ID", "Employee name", "Task ID", "Task name", "Milestone name", "Task Status"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        ButtonMAddTask.setText("Add a task");
        ButtonMAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMAddTaskActionPerformed(evt);
            }
        });

        ButtonMEditTask.setText("Edit a task");
        ButtonMEditTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMEditTaskActionPerformed(evt);
            }
        });

        ButtonMDeleteTask.setText("Delete a task");
        ButtonMDeleteTask.setMaximumSize(new java.awt.Dimension(83, 23));
        ButtonMDeleteTask.setMinimumSize(new java.awt.Dimension(83, 23));
        ButtonMDeleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMDeleteTaskActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Tasks");

        ComboBoxProjectStatus
                .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On-going", "To do", "Completed" }));
        ComboBoxProjectStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxProjectStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane3,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 955,
                                                                Short.MAX_VALUE)
                                                        .addComponent(jScrollPane1)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(ComboBoxProjectStatus,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 89,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(ButtonAddProject)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(ButtonEditProject,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(ButtonDeleteProject,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 115,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(TFEmpID,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 69,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jScrollPane4,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 955,
                                                                Short.MAX_VALUE))
                                                .addGap(36, 36, 36))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ButtonAddMilestone)
                                                .addGap(18, 18, 18)
                                                .addComponent(ButtonEditMilestone,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ButtonDeleteMilestone,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ButtonMAddTask)
                                                .addGap(18, 18, 18)
                                                .addComponent(ButtonMEditTask, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ButtonMDeleteTask, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TFEmpID, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(ButtonAddProject)
                                        .addComponent(ButtonEditProject)
                                        .addComponent(ButtonDeleteProject, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ComboBoxProjectStatus, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(ButtonAddMilestone)
                                        .addComponent(ButtonEditMilestone)
                                        .addComponent(ButtonDeleteMilestone, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(ButtonMAddTask)
                                        .addComponent(ButtonMEditTask)
                                        .addComponent(ButtonMDeleteTask, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(40, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDeleteProjectActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonDeleteProjectActionPerformed
        // TODO add your handling code here:
        JTextField projectid = new JTextField();

        final JComponent[] inputs = new JComponent[] {
                new JLabel("Project ID"),
                projectid,

        };
        JOptionPane.showConfirmDialog(null, inputs, "Delete a project", JOptionPane.PLAIN_MESSAGE);

    }// GEN-LAST:event_ButtonDeleteProjectActionPerformed

    private void ButtonEditProjectActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonEditProjectActionPerformed
        // TODO add your handling code here:
        JTextField projectid = new JTextField();

        final JComponent[] inputs = new JComponent[] {
                new JLabel("Project ID"),
                projectid,

        };
        JOptionPane.showConfirmDialog(null, inputs, "Edit a project", JOptionPane.PLAIN_MESSAGE);
    }// GEN-LAST:event_ButtonEditProjectActionPerformed

    private void ButtonAddProjectActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonAddProjectActionPerformed
        // to add a new project in the 'PROJECT' table with input dialog box
        JTextField projectname = new JTextField();
        JTextField startdate = new JTextField();
        JTextField duedate = new JTextField();
        final JComponent[] inputs = new JComponent[] {
                new JLabel("Project name"),
                projectname,
                new JLabel("Start date"),
                startdate,
                new JLabel("Due date"),
                duedate
        };
        JOptionPane.showConfirmDialog(null, inputs, "Add a project", JOptionPane.PLAIN_MESSAGE);

    }// GEN-LAST:event_ButtonAddProjectActionPerformed

    private void TFEmpIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TFEmpIDActionPerformed
        // fetch the ID of the signed-in manager in this TextField
    }// GEN-LAST:event_TFEmpIDActionPerformed

    private void ButtonDeleteMilestoneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonDeleteMilestoneActionPerformed
        // TODO add your handling code here:
        JTextField milestoneid = new JTextField();

        final JComponent[] inputs = new JComponent[] {
                new JLabel("Milestone ID"),
                milestoneid,

        };
        JOptionPane.showConfirmDialog(null, inputs, "Delete a milestone", JOptionPane.PLAIN_MESSAGE);
    }// GEN-LAST:event_ButtonDeleteMilestoneActionPerformed

    private void ButtonEditMilestoneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonEditMilestoneActionPerformed
        // TODO add your handling code here:
        JTextField milestoneid = new JTextField();

        final JComponent[] inputs = new JComponent[] {
                new JLabel("Milestone ID"),
                milestoneid,

        };
        JOptionPane.showConfirmDialog(null, inputs, "Edit a milestone", JOptionPane.PLAIN_MESSAGE);

    }// GEN-LAST:event_ButtonEditMilestoneActionPerformed

    private void ButtonAddMilestoneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonAddMilestoneActionPerformed
        // TODO add your handling code here:
        JTextField milestonename = new JTextField();
        JTextField deliverables = new JTextField();
        JTextField duedate = new JTextField();
        final JComponent[] inputs = new JComponent[] {
                new JLabel("Milestone name"),
                milestonename,
                new JLabel("Deliverables"),
                deliverables,
                new JLabel("Due date"),
                duedate
        };
        JOptionPane.showConfirmDialog(null, inputs, "Add a Milestone", JOptionPane.PLAIN_MESSAGE);
    }// GEN-LAST:event_ButtonAddMilestoneActionPerformed

    private void ButtonMAddTaskActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonMAddTaskActionPerformed
        // TODO add your handling code here:
        JTextField taskname = new JTextField();
        JTextField employeename = new JTextField();
        JTextField milestonename = new JTextField();
        final JComponent[] inputs = new JComponent[] {
                new JLabel("Task name"),
                taskname,
                new JLabel("Assign to"),
                employeename,
                new JLabel("Milestone name"),
                milestonename
        };
        JOptionPane.showConfirmDialog(null, inputs, "Add a Task", JOptionPane.PLAIN_MESSAGE);

    }// GEN-LAST:event_ButtonMAddTaskActionPerformed

    private void ButtonMEditTaskActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonMEditTaskActionPerformed
        // TODO add your handling code here:
        JTextField taskid = new JTextField();

        final JComponent[] inputs = new JComponent[] {
                new JLabel("Task ID"),
                taskid,

        };
        JOptionPane.showConfirmDialog(null, inputs, "Edit a task", JOptionPane.PLAIN_MESSAGE);
    }// GEN-LAST:event_ButtonMEditTaskActionPerformed

    private void ButtonMDeleteTaskActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonMDeleteTaskActionPerformed
        // TODO add your handling code here:
        JTextField taskid = new JTextField();

        final JComponent[] inputs = new JComponent[] {
                new JLabel("Task ID"),
                taskid,

        };
        JOptionPane.showConfirmDialog(null, inputs, "Delete a task", JOptionPane.PLAIN_MESSAGE);

    }// GEN-LAST:event_ButtonMDeleteTaskActionPerformed

    private void ComboBoxProjectStatusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ComboBoxProjectStatusActionPerformed

        int choice = ComboBoxProjectStatus.getSelectedIndex();
        switch (choice) {
            case 0:
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        Utilities.parseToObjectArray(projectDao.getOngoingProjectsForManager(manager.id)),
                        new String[] {
                                "Project ID", "Project name", "Start date", "Due date"
                        }) {
                    boolean[] canEdit = new boolean[] {
                            false, false, true, true
                    };

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit[columnIndex];
                    }
                });
                break;

            case 1:
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][] {
                                { null, null, null, null },
                                { null, null, null, null },
                                { null, null, null, null }
                        },
                        new String[] {
                                "Project ID", "Project name", "Start date", "Due date"
                        }) {
                    boolean[] canEdit = new boolean[] {
                            false, false, true, true
                    };

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit[columnIndex];
                    }
                });
                break;
            case 2:
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][] {
                                { null, null, null, null },
                                { null, null, null, null },
                                { null, null, null, null }
                        },
                        new String[] {
                                "Project ID", "Project name", "Start date", "Due date"
                        }) {
                    boolean[] canEdit = new boolean[] {
                            false, false, true, true
                    };

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit[columnIndex];
                    }
                });
                break;
            default:
                break;
        }

    }// GEN-LAST:event_ComboBoxProjectStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void build(Manager loggedInManager) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerDashboard(loggedInManager).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddMilestone;
    private javax.swing.JButton ButtonAddProject;
    private javax.swing.JButton ButtonDeleteMilestone;
    private javax.swing.JButton ButtonDeleteProject;
    private javax.swing.JButton ButtonEditMilestone;
    private javax.swing.JButton ButtonEditProject;
    private javax.swing.JButton ButtonMAddTask;
    private javax.swing.JButton ButtonMDeleteTask;
    private javax.swing.JButton ButtonMEditTask;
    private javax.swing.JComboBox<String> ComboBoxProjectStatus;
    private javax.swing.JTextField TFEmpID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private Manager manager;
    private ManagerView managerView = new ManagerView();
    private ProjectDao projectDao=new ProjectDao();


    // End of variables declaration//GEN-END:variables
}
